jobs:
  - job: build_agent_autoscaler_image
    pool:
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 20
    steps:
    - task: Docker@2
      displayName: 'Login to Container registry'
      inputs:
        command: login
        containerRegistry: githubContainerRegistry
    - task: Docker@2
      displayName: 'Build and push'
      inputs:
        repository: ghcr.io/tereius/agent-autoscaler
        Dockerfile: agent-autoscaler/Dockerfile
        buildContext: agent-autoscaler/
        command: buildAndPush
        tags: |
          $(Build.SourceBranchName)
          latest
    - task: Docker@2
      displayName: 'Logout'
      inputs:
        command: logout
        containerRegistry: githubContainerRegistry
